name: polymer2_builder
version: 0.1.0
description: Polymer2 Support for dart2ts
dependencies:
 html5: any
dev_dependencies:
 dart2ts:
  path: ../dart2ts
 build: ">=0.11.2"
 build_runner: ">=0.6.1"
 analyzer: ">=0.30.0 <0.32.0"
 polymer2:
  path: ../polymer2
dependency_overrides:
 html5:
  path: ../../html5


environment:
    sdk: ">=1.8.0 <2.0.0"
