name: polymer2_test
description: sample_project to be translated
version: 0.0.1
dependencies:
 js: any
 html5: any
 polymer2:
  path: ../polymer2
 #polymerize: any
 analyzer: ">=0.30.0 <0.32.0"
dependency_overrides:
 html5:
  path: ../../html5
dev_dependencies:
 polymer2_builder:
  path: ../polymer2_builder
 dart2ts:
  path: ../dart2ts
